import { chromium } from 'playwright';
import sharp from 'sharp';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { CARDS, CARD_BY_ID, STORAGE_KEY, parseCollection } from '../src/collection.js';
import { checkRoomControls } from './controls-browser.mjs';
import { checkCityGeometry } from './city-geometry-browser.mjs';
import { checkWorldQOL } from './world-qol-browser.mjs';
import { checkParallelRoomLoading, checkPausedRendering, checkRoomCacheFidelity, checkRoomDepthAlignment } from './performance-browser.mjs';
import { checkImmersionUI } from './immersion-browser.mjs';
import { checkCardFinishes } from './card-finishes-browser.mjs';
import { checkBuildingMassing } from './building-massing-browser.mjs';
import { checkAuditFixes } from './review-fixes-browser.mjs';
import { checkRoomNooks } from './room-nooks-browser.mjs';
import { checkGraphicsControls } from './graphics-browser.mjs';
import { checkRoomToneMapping } from './room-render-cache-browser.mjs';
import { checkMobileUX } from './mobile-ux-browser.mjs';

const origin = process.env.BINDER_URL || 'http://127.0.0.1:4173';
const shots = new URL('../../shots/binder/', import.meta.url);
await fs.mkdir(shots, { recursive: true });
const browserOptions = { headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] };
let browser = await chromium.launch(browserOptions);
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const snapshot = async target => {
  await target.waitForFunction(() => document.documentElement.dataset.saveState !== 'saving');
  return target.evaluate(key => JSON.parse(localStorage.getItem(key)), STORAGE_KEY);
};
const queue = target => target.locator('#hand-cards li').evaluateAll(items => items.map(item => item.dataset.handId));
const selection = target => target.locator('#hand-cards [aria-pressed="true"]').evaluateAll(items => items[0]?.dataset.handSelect || null);
const slot = (target, index) => target.locator(`#pocket-hotspots [data-slot="${index}"]`);
const waitSpread = (target, spread) => target.waitForFunction(({ key, spread }) => JSON.parse(localStorage.getItem(key)).spread === spread, { key: STORAGE_KEY, spread });
const ready = async target => {
  await target.goto(origin);
  await target.waitForFunction(() => document.documentElement.dataset.ready, null, { timeout: 60000 });
  await target.locator('#scene-loading').waitFor({ state: 'hidden' });
};
const shot = (target, name) => target.screenshot({ path: new URL(name, shots).pathname });
const importLayout = async (target, state) => {
  await target.locator('#help-open').click();
  await target.locator('#import-file').setInputFiles({ name: 'layout.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(state)) });
  await target.locator('[data-close="help-dialog"]').click();
  await waitSpread(target, state.spread);
};
async function changedPixels(first, second) {
  const a = await sharp(first).removeAlpha().raw().toBuffer();
  const b = await sharp(second).removeAlpha().raw().toBuffer();
  assert.equal(a.length, b.length);
  let count = 0;
  for (let i = 0; i < a.length; i += 3) if (Math.abs(a[i] - b[i]) + Math.abs(a[i + 1] - b[i + 1]) + Math.abs(a[i + 2] - b[i + 2]) > 12) count++;
  return count;
}

try {
  await ready(page);
  assert.equal(await page.locator('html').getAttribute('data-ready'), 'true');
  assert.equal(await page.evaluate(() => performance.getEntriesByType('resource').some(entry => entry.name.includes('tokyo-night.webp'))), false, 'The app must not fetch the old photographic skyline');
  assert.equal(await page.locator('html').getAttribute('aria-pressed'), null);
  await page.locator('.pocket-hotspot').first().waitFor();
  assert.equal(await page.locator('.pocket-hotspot').count(), 18);
  const initial = await snapshot(page);
  await shot(page, 'desktop.png');

  for (const index of [9, 10, 11]) await slot(page, index).click();
  const picked = [initial.slots[9], initial.slots[10], initial.slots[11]];
  assert.deepEqual(await queue(page), picked);
  assert.equal(await page.locator('#inspect-dialog').isVisible(), false);
  assert.equal(await page.locator('#collection-count').textContent(), '11');
  assert.deepEqual(await snapshot(page), initial, 'Pickup alone must not mutate the saved layout');
  await slot(page, 17).hover();
  assert.equal(await slot(page, 17).evaluate(element => element.classList.contains('is-drop-target')), true);
  await shot(page, 'hand-queue.png');
  await slot(page, 17).click();
  assert.equal((await snapshot(page)).slots[17], picked[0]);
  assert.deepEqual(await queue(page), picked.slice(1));
  await page.keyboard.press('ArrowRight'); await waitSpread(page, 2);
  await slot(page, 27).click(); await slot(page, 29).click();
  const placed = await snapshot(page);
  assert.equal(placed.slots[27], picked[1]); assert.equal(placed.slots[29], picked[2]);
  assert.deepEqual(await queue(page), []);
  assert.equal(await page.locator('#hand-tray').isVisible(), false);
  await page.locator('#undo-action').click();
  assert.equal((await snapshot(page)).slots[29], null);
  assert.deepEqual(await queue(page), [picked[2]]);
  await page.keyboard.press('Escape');
  assert.deepEqual(await queue(page), []);
  parseCollection(JSON.stringify(await snapshot(page)));
  console.log('PASS: single-click pickup, multi-card FIFO across pages, highlighted placement, cancel and undo');

  await importLayout(page, initial);
  for (const index of [9, 10, 11]) await slot(page, index).click();
  const minimalHand = await page.locator('#hand-tray').evaluate(element => {
    const style = getComputedStyle(element);
    return { background: style.backgroundColor, border: style.borderTopWidth, buttons: element.querySelectorAll('[data-hand-select]').length, select: element.querySelectorAll('select').length };
  });
  assert.equal(minimalHand.background, 'rgba(0, 0, 0, 0)');
  assert.equal(minimalHand.border, '0px');
  assert.equal(minimalHand.buttons, 3);
  assert.equal(minimalHand.select, 0);
  await page.locator(`[data-hand-select="${picked[2]}"]`).click();
  assert.equal(await selection(page), picked[2]);
  assert.deepEqual(await queue(page), picked);
  assert.equal(await page.locator('#inspect-dialog').isVisible(), false, 'A single hand click selects without opening a menu');
  await page.keyboard.press('e');
  assert.equal(await page.locator('#inspect-name').textContent(), CARD_BY_ID.get(picked[2]).name);
  await page.locator('[data-close="inspect-dialog"]').click();
  await page.keyboard.press('ArrowRight'); await waitSpread(page, 2);
  await slot(page, 27).hover();
  assert.match(await page.locator('#drop-hint').textContent(), new RegExp(CARD_BY_ID.get(picked[2]).name));
  await shot(page, 'selected-hand.png');
  await slot(page, 27).click();
  assert.equal((await snapshot(page)).slots[27], picked[2]);
  assert.deepEqual(await queue(page), picked.slice(0, 2));
  assert.equal(await selection(page), picked[0]);
  await page.locator('#undo-action').click();
  assert.equal(await selection(page), picked[2]);
  assert.deepEqual(await queue(page), picked);
  await page.keyboard.press('Delete');
  assert.deepEqual(await queue(page), picked.slice(0, 2));
  await page.locator(`[data-hand-select="${picked[1]}"]`).dblclick();
  assert.equal(await page.locator('#inspect-name').textContent(), CARD_BY_ID.get(picked[1]).name);
  await page.locator('[data-close="inspect-dialog"]').click();
  assert.equal(await selection(page), picked[1]);
  await page.keyboard.press('Escape');
  console.log('PASS: cards-only hand, active selection, inspection, non-FIFO placement, selection-aware undo and Delete');

  await importLayout(page, initial);
  await slot(page, 9).click(); await slot(page, 10).click();
  await slot(page, 10).click();
  assert.equal((await snapshot(page)).slots[10], initial.slots[9]);
  assert.deepEqual(await queue(page), [initial.slots[10]]);
  await page.keyboard.press('Escape');
  assert.equal((await snapshot(page)).slots[9], initial.slots[10]);
  assert.equal((await snapshot(page)).slots[10], initial.slots[9]);
  console.log('PASS: vacated queued pockets can be refilled without losing displaced queued cards');

  await importLayout(page, initial);
  await page.keyboard.press('b');
  await page.locator('#card-search').fill('pikachu 023');
  assert.equal(await page.locator('.collection-card').count(), 1);
  await page.locator('#card-search').press('ArrowLeft');
  assert.equal((await snapshot(page)).spread, 1);
  await page.locator('#card-search').fill('not a real card match');
  assert.equal(await page.locator('#bag-empty').isVisible(), true);
  await page.locator('#clear-filters').click();
  await page.locator('[data-location="bag"]').click();
  const bagIds = await page.locator('.collection-card').evaluateAll(elements => elements.slice(0, 4).map(element => element.dataset.cardId));
  for (const id of bagIds.slice(0, 3)) await page.locator(`.collection-card[data-card-id="${id}"]`).click();
  assert.equal(await page.locator('#bag-dialog').isVisible(), true, 'Bag stays open for batch pickup');
  assert.deepEqual(await queue(page), bagIds.slice(0, 3));
  await page.locator(`.collection-card[data-card-id="${bagIds[1]}"]`).click();
  await page.locator(`.collection-card[data-card-id="${bagIds[1]}"]`).click();
  assert.deepEqual(await queue(page), [bagIds[0], bagIds[2], bagIds[1]]);
  await page.locator('#sort-filter').selectOption('name');
  assert.deepEqual(await queue(page), [bagIds[0], bagIds[2], bagIds[1]], 'Filtering and sorting must not reorder the hand');
  await page.locator('#card-search').fill('pikachu');
  await shot(page, 'bag.png');
  await page.locator('#clear-filters').click();
  await page.locator(`.card-inspect-button[data-inspect-id="${bagIds[0]}"]`).click();
  await page.locator('#inspect-dialog').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#hold-card').isDisabled(), true);
  await page.locator('#flip-inspection').click(); assert.equal(await page.locator('.sleeve-back').count(), 1);
  await page.locator('#flip-inspection').click();
  await page.waitForTimeout(350); await shot(page, 'inspection.png');
  await page.locator('[data-close="inspect-dialog"]').click();
  await page.locator('#bag-place').click();
  for (const index of [17, 20, 26]) await slot(page, index).click();
  const arranged = await snapshot(page);
  assert.deepEqual([arranged.slots[17], arranged.slots[20], arranged.slots[26]], [bagIds[0], bagIds[2], bagIds[1]]);
  await page.locator('#bag-open').click(); await page.locator('[data-location="bag"]').click();
  const beforeUndo = await page.locator('.collection-card').count();
  await page.locator('[data-location="bag"]').focus(); await page.keyboard.press('Control+z');
  assert.equal(await page.locator('.collection-card').count(), beforeUndo + 1, 'Undo refreshes bag filter membership');
  assert.deepEqual(await queue(page), [bagIds[1]]);
  await page.locator('[data-close="bag-dialog"]').click(); await slot(page, 26).click();
  await page.reload();
  await page.waitForFunction(() => document.documentElement.dataset.ready === 'true', null, { timeout: 60000 });
  await page.locator('#scene-loading').waitFor({ state: 'hidden' });
  assert.deepEqual(await snapshot(page), arranged);
  console.log('PASS: batch bag selection, deselection, stable ordering, separate inspection and saved placements');

  await page.locator('#bag-open').click();
  const restored = CARDS.find(card => card.name === 'Chimchar' && card.number === 'MEP 041');
  assert.ok(restored?.imageVerification, 'The formerly pending Chimchar has a recorded visual review');
  await page.locator('#card-search').fill(restored.name);
  await page.locator(`.card-inspect-button[data-inspect-id="${restored.id}"]`).click();
  assert.equal(await page.locator('#inspect-pending').isVisible(), false);
  await page.waitForFunction(() => {
    const image = document.querySelector('#inspection-card img');
    return image?.complete && image.naturalWidth > 0;
  });
  assert.equal(await page.locator('#inspection-card .pending-art').count(), 0);
  await page.locator('#hold-card').click();
  assert.deepEqual(await queue(page), [restored.id]);
  await page.locator('[data-close="bag-dialog"]').click(); await page.keyboard.press('Escape');
  await importLayout(page, initial);
  const label = await page.locator('#pile-unsorted').boundingBox();
  for (let i = 0; i < 3; i++) await page.mouse.click(label.x + label.width / 2, label.y + label.height / 2 - 45);
  assert.deepEqual(await queue(page), initial.piles.unsorted.slice(0, 3));
  await page.locator('#pile-trades').click(); await page.locator('#pile-trades').click();
  assert.deepEqual((await snapshot(page)).piles.trades.slice(0, 2), [initial.piles.unsorted[1], initial.piles.unsorted[0]]);
  assert.deepEqual(await queue(page), [initial.piles.unsorted[2]]);
  await page.keyboard.press('e');
  await page.locator('#inspect-return').click();
  assert.deepEqual(await queue(page), []);
  await page.locator('#pile-favorites').click();
  await page.locator('#sort-filter').selectOption('name'); await page.locator('#sort-stack').click();
  const names = (await snapshot(page)).piles.favorites.map(id => CARD_BY_ID.get(id).name);
  assert.deepEqual(names, [...names].sort((a, b) => a.localeCompare(b)));
  await page.locator('[data-close="bag-dialog"]').click();
  console.log('PASS: restored artwork, repeated table-stack pickup, FIFO table/bag destinations and physical sorting');

  await importLayout(page, initial);
  await page.locator('#bag-open').click(); await page.locator('#clear-filters').click();
  const keyboardCard = page.locator('.collection-card').first();
  const keyboardId = await keyboardCard.getAttribute('data-card-id');
  await keyboardCard.focus(); await keyboardCard.press('Enter');
  assert.deepEqual(await queue(page), [keyboardId]);
  assert.equal(await keyboardCard.evaluate(element => document.activeElement === element), true);
  await page.locator('[data-close="bag-dialog"]').click();
  await page.locator('#flat-open').click();
  await page.locator('.flat-pocket[data-slot="17"]').focus();
  await page.locator('.flat-pocket[data-slot="17"]').press('Enter');
  assert.equal((await snapshot(page)).slots[17], keyboardId);
  await page.locator('#flat-previous').click(); await waitSpread(page, 0);
  assert.equal(await page.locator('.flat-pocket').count(), 9);
  assert.equal(await page.locator('#flat-previous').isDisabled(), true);
  for (let spread = 1; spread < 21; spread++) { await page.locator('#flat-next').click(); await waitSpread(page, spread); }
  assert.equal(await page.locator('.flat-pocket').count(), 9);
  assert.equal(await page.locator('#flat-next').isDisabled(), true);
  await page.locator('[data-close="flat-dialog"]').click();
  console.log('PASS: keyboard selection and placement, all 21 spreads, and cover boundaries');

  await page.locator('#help-open').click();
  const beforeImport = await snapshot(page), invalid = structuredClone(beforeImport);
  invalid.slots[0] = invalid.slots[17];
  await page.locator('#import-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(invalid)) });
  await page.waitForFunction(() => document.querySelector('#help-dialog .dialog-notice')?.textContent.startsWith('Could not import'));
  assert.match(await page.locator('#help-dialog .dialog-notice').textContent(), /Could not import/);
  assert.deepEqual(await snapshot(page), beforeImport);
  await page.locator('#import-file').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(initial)) });
  await waitSpread(page, 1);
  const downloadEvent = page.waitForEvent('download'); await page.locator('#export-layout').click();
  const download = await downloadEvent, stream = await download.createReadStream(), chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  assert.deepEqual(parseCollection(Buffer.concat(chunks).toString()), initial);
  await page.locator('[data-close="help-dialog"]').click();
  const finalSpread = { ...initial, spread: 20 };
  await page.evaluate(layout => {
    document.getElementById('next-page').click();
    document.getElementById('help-open').click();
    if (!document.getElementById('import-layout').disabled) throw new Error('The turn was not started for the import regression.');
    const input = document.getElementById('import-file'), transfer = new DataTransfer();
    transfer.items.add(new File([JSON.stringify(layout)], 'during-turn.json', { type: 'application/json' }));
    input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true }));
  }, finalSpread);
  await page.waitForFunction(() => document.querySelector('#help-dialog .dialog-notice')?.textContent.includes('finish turning'));
  await waitSpread(page, 2);
  assert.equal((await snapshot(page)).spread, 2, 'An import must not replace state underneath a pending page turn');
  await page.locator('[data-close="help-dialog"]').click(); await page.keyboard.press('ArrowLeft'); await waitSpread(page, 1);
  const edge = await slot(page, 23).evaluate(button => {
    const rect = button.getBoundingClientRect(), points = button.style.clipPath.match(/[\d.]+/g).map(Number);
    return { x: rect.x + (points[2] + points[4]) / 200 * rect.width + 9, y: rect.y + rect.height / 2 };
  });
  await page.mouse.move(edge.x, edge.y); await page.mouse.down(); await page.mouse.move(edge.x - 230, edge.y - 12, { steps: 14 }); await page.mouse.up();
  await waitSpread(page, 2); await page.keyboard.press('ArrowLeft'); await waitSpread(page, 1);
  console.log('PASS: validated import/export and physical mouse page turns remain available');

  await page.locator('#room-view').click(); await page.waitForTimeout(1200);
  await page.locator('#help-open').click(); await page.locator('.weather-options [data-weather="rain"]').click();
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(400);
  await page.mouse.move(12, 880);
  const rainA = await page.locator('#room-canvas').screenshot(); await page.waitForTimeout(850);
  const rainB = await page.locator('#room-canvas').screenshot();
  assert.ok(await changedPixels(rainA, rainB) > 600, 'Rain and city features must visibly move, not only update state');
  await shot(page, 'room-rain.png');
  await page.locator('#help-open').click(); await page.locator('.weather-options [data-weather="clear"]').click();
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(400);
  const clearA = await page.locator('#room-canvas').screenshot(); await page.waitForTimeout(1300);
  const clearB = await page.locator('#room-canvas').screenshot();
  assert.ok(await changedPixels(clearA, clearB) > 50, 'Traffic, aircraft and beacons must move even without rain');
  await page.locator('#help-open').click(); await page.locator('#city-motion-toggle').click();
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(400);
  const pausedA = await page.locator('#room-canvas').screenshot(); await page.waitForTimeout(550);
  const pausedB = await page.locator('#room-canvas').screenshot();
  assert.equal(await changedPixels(pausedA, pausedB), 0, 'Pause must stop every automatic city animation');
  await page.locator('#help-open').click(); await page.locator('.weather-options [data-weather="fog"]').click();
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(400);
  const fog = await page.locator('#room-canvas').screenshot();
  assert.ok(await changedPixels(pausedB, fog) > 2000, 'Fog must visibly change the atmosphere');
  await shot(page, 'room-fog.png');
  await page.locator('#weather-toggle').click();
  assert.equal(await page.locator('html').getAttribute('data-weather'), 'clear');
  await page.locator('#weather-toggle').click();
  assert.equal(await page.locator('html').getAttribute('data-weather'), 'rain');
  await page.waitForTimeout(400);
  const frozenRainA = await page.locator('#room-canvas').screenshot(); await page.waitForTimeout(450);
  const frozenRainB = await page.locator('#room-canvas').screenshot();
  assert.equal(await changedPixels(frozenRainA, frozenRainB), 0, 'Rain must also remain frozen while city motion is paused');
  const binderRegion = { left: 310, top: 545, width: 770, height: 200 };
  await page.locator('#time-preset').selectOption('day');await page.waitForTimeout(500);
  const beforeRelighting = await sharp(await page.screenshot()).extract(binderRegion).png().toBuffer();
  await page.locator('#help-open').click();
  await page.locator('#city-time').fill('22');
  assert.equal(await page.locator('#city-time-label').textContent(), '22:00');
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(500);
  const nightInterior = await sharp(await page.screenshot()).extract(binderRegion).png().toBuffer();
  assert.ok(await changedPixels(beforeRelighting, nightInterior) > 500, 'Daylight through the window should subtly relight the apartment instead of leaving it identical at every hour');
  await page.locator('#help-open').click();
  await page.locator('#city-windows').uncheck();
  await page.locator('#city-tower').uncheck();
  await page.locator('[data-close="help-dialog"]').click(); await page.waitForTimeout(500);
  const afterRelighting = await sharp(await page.screenshot()).extract(binderRegion).png().toBuffer();
  assert.equal(await changedPixels(nightInterior, afterRelighting), 0, 'Exterior window/tower toggles must not wash out the independently lit room or binder');
  await page.locator('#city-view').click(); await page.waitForTimeout(1400);
  assert.equal(await page.locator('#city-view').getAttribute('aria-pressed'), 'true');
  await shot(page, 'balcony-3d.png');
  await page.locator('#help-open').click();
  await page.locator('#city-time').fill('17.75');
  await page.locator('#city-windows').check(); await page.locator('#city-tower').check();
  await page.locator('[data-close="help-dialog"]').click();
  await page.locator('#binder-view').click(); await page.waitForTimeout(1400);
  assert.equal(await page.locator('.pocket-hotspot:visible').count(), 18);
  assert.deepEqual(errors, [], `Unexpected browser errors: ${errors.join('; ')}`);
  console.log('PASS: city motion, weather, complete pause, independent city relighting and balcony navigation');
  await context.close();

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const mobile = await mobileContext.newPage(); await ready(mobile);
  assert.equal(await mobile.locator('html').getAttribute('data-city-motion'), 'paused');
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await mobile.locator('#bag-open').tap(); await mobile.locator('[data-location="bag"]').tap();
  const mobileIds = await mobile.locator('.collection-card').evaluateAll(elements => elements.slice(0, 3).map(element => element.dataset.cardId));
  for (const id of mobileIds) await mobile.locator(`.collection-card[data-card-id="${id}"]`).tap();
  assert.deepEqual(await queue(mobile), mobileIds);
  const cdp = await mobileContext.newCDPSession(mobile), grid = await mobile.locator('#card-grid').boundingBox();
  const scrollBefore=await mobile.locator('#bag-dialog').evaluate(element=>element.scrollTop);
  const footer=await mobile.locator('.bag-footer').boundingBox();
  const touchX = grid.x + grid.width / 2, touchY = Math.min(600,footer.y-30);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchX, y: touchY, id: 1 }] });
  for (let i = 1; i <= 6; i++) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchX, y: touchY - i * 24, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await mobile.waitForFunction(before=>document.getElementById('bag-dialog').scrollTop>before,scrollBefore);
  assert.deepEqual(await queue(mobile), mobileIds, 'Scrolling the bag must not pick up more cards');
  await mobile.locator('#bag-place').tap();
  await mobile.locator(`[data-hand-select="${mobileIds[2]}"]`).tap();
  assert.equal(await selection(mobile), mobileIds[2]);
  await shot(mobile, 'mobile-hand.png');
  for (const index of [17, 20, 26]) await slot(mobile, index).tap();
  const mobileState = await snapshot(mobile);
  assert.deepEqual([mobileState.slots[17], mobileState.slots[20], mobileState.slots[26]], [mobileIds[2], mobileIds[0], mobileIds[1]]);
  await mobile.locator('#next-page').tap(); await waitSpread(mobile, 2);
  await mobile.setViewportSize({ width: 844, height: 390 });
  await mobile.locator('#bag-open').tap(); await mobile.locator('.card-inspect-button').first().tap();
  assert.equal(await mobile.locator('#inspect-dialog').isVisible(), true);
  await mobileContext.close();
  console.log('PASS: mobile FIFO taps, native bag scrolling, landscape inspection and reduced-motion default');

  const fallbackContext = await browser.newContext({ viewport: { width: 1100, height: 800 } });
  await fallbackContext.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (type, ...args) {
      if (['webgl2', 'webgl', 'experimental-webgl'].includes(type)) return null;
      return original.call(this, type, ...args);
    };
  });
  const fallback = await fallbackContext.newPage(); await ready(fallback);
  assert.equal(await fallback.locator('html').getAttribute('data-ready'), 'fallback');
  await fallback.locator('#fallback-open').click();
  await fallback.locator('.flat-pocket[data-slot="9"]').click(); await fallback.locator('.flat-pocket[data-slot="10"]').click();
  await fallback.locator('#flat-selected-card').selectOption(initial.slots[10]);
  await fallback.locator('.flat-pocket[data-slot="17"]').click(); await fallback.locator('.flat-pocket[data-slot="20"]').click();
  assert.deepEqual([(await snapshot(fallback)).slots[17], (await snapshot(fallback)).slots[20]], [initial.slots[10], initial.slots[9]]);
  await fallbackContext.close();

  const missingCityContext = await browser.newContext({ viewport: { width: 1100, height: 800 } });
  await missingCityContext.route('**/city/manifest.json.gz', route => route.fulfill({ status: 503, body: 'Survey assets unavailable' }));
  const missingCity = await missingCityContext.newPage(); await ready(missingCity);
  assert.equal(await missingCity.locator('html').getAttribute('data-ready'), 'true', 'Missing city data must not prevent the 3D binder from opening');
  assert.equal(await missingCity.locator('html').getAttribute('data-city-status'), 'degraded');
  assert.equal(await missingCity.locator('#city-load-warning').isVisible(), true);
  assert.deepEqual(await snapshot(missingCity), initial, 'A city load failure must not alter the saved collection');
  await missingCity.locator('#flat-open').click();
  await missingCity.locator('.flat-pocket[data-slot="9"]').click();
  await missingCity.locator('.flat-pocket[data-slot="17"]').click();
  assert.equal((await snapshot(missingCity)).slots[17], initial.slots[9]);
  await missingCityContext.close();
  console.log('PASS: unavailable survey data is reported while the 3D binder and saved cards remain usable');

  const corruptContext = await browser.newContext();
  await corruptContext.addInitScript(key => localStorage.setItem(key, 'broken previous layout'), STORAGE_KEY);
  const corrupt = await corruptContext.newPage(); await ready(corrupt);
  assert.equal(await corrupt.locator('#storage-warning').isVisible(), true);
  assert.equal(await corrupt.evaluate(key => localStorage.getItem(key), STORAGE_KEY), 'broken previous layout');
  await corrupt.locator('#storage-retry').click();
  await corrupt.waitForFunction(() => document.documentElement.dataset.saveState === 'saved');
  parseCollection(await corrupt.evaluate(key => localStorage.getItem(key), STORAGE_KEY));
  await corruptContext.close();
  console.log('PASS: no-WebGL queued-hand fallback and corrupt-save protection');
  await checkRoomControls(browser, origin, shots);
  await checkCityGeometry(browser, origin, shots);
  await checkPausedRendering(browser,origin);
  await checkRoomDepthAlignment(browser,origin,shots);
  await checkRoomDepthAlignment(browser,origin,shots,'auto');
  await checkRoomCacheFidelity(browser,origin);
  await checkRoomToneMapping(browser,origin);
  await checkGraphicsControls(browser,origin,shots);
  // Release accumulated GPU/process caches before the second independent browser cohort.
  await browser.close();browser=await chromium.launch(browserOptions);
  await checkParallelRoomLoading(browser,origin);
  await checkWorldQOL(browser, origin, shots);
  await checkImmersionUI(browser,origin,shots);
  await checkRoomNooks(browser,origin);
  await checkMobileUX(browser,origin,shots);
  await checkCardFinishes(browser,origin,shots);
  await checkBuildingMassing(browser,origin,shots);
  await checkAuditFixes(browser,origin,shots);
  console.log('All binder, living-city and room-control browser checks passed.');
} catch (error) {
  if (!page.isClosed()) await shot(page, 'test-failure.png');
  throw error;
} finally {
  await browser.close();
}
